name: Cache Dependencies

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'package*.json'
      - 'yarn.lock'
      - '**/package*.json'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'package*.json'
      - 'yarn.lock'
      - '**/package*.json'

jobs:
  cache-dependencies:
    name: Cache Node.js Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Cache Capacitor dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
            ios/Pods
          key: ${{ runner.os }}-capacitor-${{ hashFiles('**/Podfile.lock', '**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-capacitor-

  cache-build-artifacts:
    name: Cache Build Artifacts
    runs-on: ubuntu-latest
    needs: cache-dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Cache www build
        uses: actions/cache@v4
        with:
          path: www/
          key: ${{ runner.os }}-www-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-www-